server.port=${CRAZY_TRACKER_PORT_LOCAL}

spring.datasource.url=${CRAZY_TRACKER_DB_URL_LOCAL}
spring.datasource.username=${CRAZY_TRACKER_DB_USERNAME_LOCAL}
spring.datasource.password=${CRAZY_TRACKER_DB_PASSWORD_LOCAL}
spring.liquibase.change-log=${URL_LIQUIBASE}

#token.signing.key=${JWT_SIGNING_KEY}
token.signing.key=53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855