server.port=${CRAZY_TRACKER_PORT_LOCAL}

spring.datasource.url=${CRAZY_TRACKER_DB_URL_LOCAL}
spring.datasource.username=${CRAZY_TRACKER_DB_USERNAME_LOCAL}
spring.datasource.password=${CRAZY_TRACKER_DB_PASSWORD_LOCAL}
spring.liquibase.change-log=${URL_LIQUIBASE}

token.signing.key=${JWT_SIGNING_KEY}

#Send email
spring.mail.host=${SMTP_GOOGLE}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${GOOGLE_NAME}
spring.mail.password=${GOOGLE_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#ElasticSearch
spring.elasticsearch.uris=${ELASTIC_SEARCH_URL_LOCAL}
spring.elasticsearch.username=${ELASTIC_SEARCH_USERNAME_LOCAL}
spring.elasticsearch.password=${ELASTIC_SEARCH_PASSWORD_LOCAL}
spring.data.elasticsearch.repositories.enabled=true

#REDIS
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.host=${REDIS_HOST:localhost}
#spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=${REDIS_TIMEOUT:2000}
