server.port=${CRAZY_TRACKER_PORT_LOCAL}

spring.datasource.url=${CRAZY_TRACKER_DB_URL_LOCAL}
spring.datasource.username=${CRAZY_TRACKER_DB_USERNAME_LOCAL}
spring.datasource.password=${CRAZY_TRACKER_DB_PASSWORD_LOCAL}
spring.liquibase.change-log=${URL_LIQUIBASE}

token.signing.key=${JWT_SIGNING_KEY}

#Send email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GOOGLE_NAME}
spring.mail.password=${GOOGLE_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true